// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © nhatnam2008

//@version=5
strategy(title="RSI_Strategy_raw", shorttitle="RSI_Stra_(R)", overlay=false, initial_capital=10000, default_qty_type=strategy.fixed, default_qty_value=10, calc_on_every_tick=false, calc_on_order_fills=false, commission_type=strategy.commission.cash_per_contract, commission_value=0.015, slippage = 100)

ma(source, length, type) =>
    switch type
        "SMA" => ta.sma(source, length)
        "Bollinger Bands" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)
///////////////////////////////////////////////////////////////////////////
rsiLengthInput = input.int(14, minval=1, title="RSI Length", group="RSI Settings 1")
rsiSourceInput = input.source(close, "Source", group="RSI Settings 1")
ob = input(70, title='Upper Threshold 1', group="RSI Settings 1")
os = input(30, title='Lower Threshold 1', group="RSI Settings 1")
maTypeInput = input.string("EMA", title="MA Type", options=["SMA", "Bollinger Bands", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group="RSI Settings 1")
maLengthInput = input.int(7, title="MA Length", group="RSI Settings 1")
maTypeInput2 = input.string("WMA", title="MA Type 2", options=["SMA", "Bollinger Bands", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group="RSI Settings 1")
maLengthInput2 = input.int(47, title="MA Length 2", group="RSI Settings 1")
stoploss = input.int(3500, minval=1, step=500, title="stoploss", group="Trade")
takeprofit = input.int(3000000, minval=1,step=5000, title="take profit", group="Trade")

rsi = ta.rsi(rsiSourceInput, rsiLengthInput)
rsiMA_small = ma(rsi, maLengthInput, maTypeInput)
rsiMA_large = ma(rsi, maLengthInput2, maTypeInput2)

// plot(rsi, "RSI14", color=color.white)
plot(rsiMA_small, "RSI-based MA", color=color.yellow)
plot(rsiMA_large, "RSI-based MA 2", color=color.blue)
rsiUpperBand = hline(ob, "RSI Upper Band", color=#787B86)
hline(50, "RSI Middle Band", color=#787B86, linestyle=hline.style_solid)
rsiLowerBand = hline(os, "RSI Lower Band", color=#787B86)

trend = rsiMA_large >= 50 ? 1 : 0
dieukien = rsiMA_small >= rsiMA_large ? 1 : 0

buy = dieukien[1] == 0 and dieukien[0] == 1 and trend == 1 ? true : false
buy_close = dieukien[1] == 0 and dieukien[0] == 0 ? true : false
sell =  dieukien[1] == 1 and dieukien[0] == 0 and trend == 0 ? true : false
sell_close = dieukien[1] == 1 and dieukien[0] == 1 ? true : false

if buy
    strategy.entry("buy", strategy.long)
    strategy.exit("exitbuy", "buy", profit = takeprofit, loss = stoploss)
if buy_close
    strategy.close('buy')
if sell
    strategy.entry("sell", strategy.short)
    strategy.exit("exitsell", "sell", profit = takeprofit, loss = stoploss)
if sell_close
    strategy.close('sell')